### ISSUE TITLE
get_region_summary() and sample names with "_"

### ISSUE THREAD

**Issue by ClarissaFeuersteinAkgoz** [CompEpigen/methrix#15]
get_region_summary() will not work if sample names have underscore "_" as they are converted into "." in the usage of the function

**Comment by tkik** [comment]
Hi, 
get_region_summary() should work with "_", but not with "-". If colData is provided, this issue is taken care of, so it can only happen if the sample names are created based on the file names. 
I added a fix to the branch devel_update - [https://github.com/CompEpigen/methrix/commit/be2a92c78a3ed8599b2c591d4b05d9ac60fec41e](url)  - that changes "-" to "." even when colData is not provided. Please read in your data again so the changes can take place.
