### ISSUE TITLE
High memory usage with read_bedgraph

### ISSUE THREAD

**Issue by jamespeapen** [CompEpigen/methrix#32]
I have some single-cell WGBS data I'm trying to read, but am having trouble with memory consumption.
There are 94 BGZIP compressed bedfiles between 4 and 500 KB each. The max CpG count among them is 64000.

```r
library(methrix)
library(BSgenome)
files <- list.files("./data/sc/k562/", full.names = TRUE, pattern = "*bed.gz$")

cpgs <- methrix::extract_CPGs(ref_genome = "BSgenome.Hsapiens.UCSC.hg38")

bs <- read_bedgraphs(
  files,
  ref_cpgs = cpgs,
  chr_idx = 1,
  start_idx = 2,
  beta_idx = 4,
  cov_idx = 5,
  stranded = FALSE,
  zero_based = TRUE,
  vect = TRUE,
  n_threads = 1
)

lobstr::obj_size(bs)
```

When running on a system with 64Gb of RAM, reading 94 bedfiles with 4 threads fails with this error:

```
Error in .(cov) : could not find function "."
In addition: Warning message:
In parallel::mclapply(batch_files, read_bdg, col_list = col_idx,  :
  scheduled cores 1, 2, 3, 4 did not deliver results, all values of the jobs will be affected
```

This scripts did work when I tried running it on an HPC, but the SLURM scheduler reports high memory usage. Although using more threads would result in higher memory usage, it seems to be increasing by a lot more than I would have expected.

```
$ sacct --format="MaxRSS" --units=g -j $JOBID

# 1 thread
    MaxRSS
----------
    62.71G

# 4 threads
    MaxRSS
----------
   270.01G

# 16 threads
    MaxRSS
----------
    300.3G
```

The `lobstr::obj_size` reported for this data once created into a methrix object is only 33 Gb. I wonder if my laptop runs out of memory and `data.table::fread` is not able to read all the files, giving the error?

Is there a way to pass in a set of CpGs so that all 29 million are not considered - only the ones I would like to analyze? Since single-cell data is so sparse, I'm hoping to reduce memory usage by only passing in relevant loci.

**Comment by tkik** [comment]
Hi @jamespeapen,

in `methrix`, you have multiple options to tailor the memory needs to your system. In the default settings `vect=FALSE` & `h5=FALSE`, it will read in 1 file at a time, keeping the memory use low. if you use the `h5=TRUE` option, it will use an hdf5 backend instead of in-memory objects, therefore further decreasing the memory use. On the other hand, using the `vect=TRUE` it will read in multiple files at a time, depending on the batch size, increasing the speed, but the memory needs as well. So I recommend you to try setting `vect=FALSE` or even `h5=TRUE`. After the reading, you can run the `remove_uncovered()` function and if the `h5=TRUE` option was used convert it to in-memory object with `convert_HDF5_methrix()`. This will take some time though.  
Alternatively, we developed a version for single-cell methylomes, which won't use the whole genome reference. you can try it here: [https://github.com/CompEpigen/scMethrix](url). Keep in mind that this is still in beta version, but I used it recently and it worked fine. 
Don't hesitate to reach out if you have further questions.

**Comment by jamespeapen** [comment]
Thanks - will try scMethrix!
